// Customized bangs

export const bangs = [
  // AI
  {
    c: "AI",
    d: "www.t3.chat",
    r: 0,
    s: "T3 Chat",
    sc: "AI",
    t: "t3",
    u: "https://www.t3.chat/new?q={{{s}}}",
  },

  // Search/Reference
  {
    c: "Online Services",
    d: "www.google.com",
    r: 1942262,
    s: "Google",
    sc: "Search",
    t: "g",
    u: "https://www.google.com/search?q={{{s}}}",
  },
  {
    c: "Online Services",
    d: "duckduckgo.com",
    r: 50000,
    s: "DuckDuckGo",
    sc: "Search",
    t: "ddg",
    u: "https://duckduckgo.com/?q={{{s}}}",
  },
  {
    c: "Reference",
    d: "en.wikipedia.org",
    r: 324464,
    s: "Wikipedia",
    sc: "Encyclopedia",
    t: "w",
    u: "https://en.wikipedia.org/wiki/Special:Search?search={{{s}}}",
  },

  // Developer/Tech
  {
    c: "Tech",
    d: "github.com",
    r: 15975,
    s: "GitHub",
    sc: "Programming",
    t: "gh",
    u: "https://github.com/search?utf8=%E2%9C%93&q={{{s}}}",
  },
  {
    c: "Tech",
    d: "npmx.dev",
    r: 4340,
    s: "npm",
    sc: "Languages (javascript)",
    t: "npm",
    u: "https://npmx.dev/search?q={{{s}}}",
  },
  {
    c: "Tech",
    d: "crates.io",
    r: 1000,
    s: "Crates.io",
    sc: "Languages (rust)",
    t: "crates",
    u: "https://crates.io/search?q={{{s}}}",
  },
  {
    c: "Tech",
    d: "pypi.org",
    r: 2000,
    s: "PyPI",
    sc: "Languages (python)",
    t: "pypi",
    u: "https://pypi.org/search/?q={{{s}}}",
  },
  {
    c: "Tech",
    d: "hub.docker.com",
    r: 3000,
    s: "Docker Hub",
    sc: "Containers",
    t: "docker",
    u: "https://hub.docker.com/search?q={{{s}}}",
  },

  // Media/Social
  {
    c: "Multimedia",
    d: "www.youtube.com",
    r: 463021,
    s: "YouTube",
    sc: "Video",
    t: "yt",
    u: "https://www.youtube.com/results?search_query={{{s}}}",
  },
  {
    c: "Multimedia",
    d: "www.twitch.tv",
    r: 50000,
    s: "Twitch",
    sc: "Video",
    t: "ttv",
    u: "https://www.twitch.tv/search?term={{{s}}}",
  },
  {
    c: "Social",
    d: "www.reddit.com",
    r: 100000,
    s: "Reddit",
    sc: "Forums",
    t: "r",
    u: "https://www.reddit.com/search?q={{{s}}}",
  },
  {
    c: "Social",
    d: "x.com",
    r: 80000,
    s: "X",
    sc: "Social",
    t: "x",
    u: "https://x.com/search?q={{{s}}}",
  },
  {
    c: "Multimedia",
    d: "open.spotify.com",
    r: 40000,
    s: "Spotify",
    sc: "Music",
    t: "sp",
    u: "https://open.spotify.com/search/{{{s}}}",
  },

  // Shopping/Services
  {
    c: "Shopping",
    d: "www.amazon.com",
    r: 200000,
    s: "Amazon",
    sc: "Shopping",
    t: "a",
    u: "https://www.amazon.com/s?k={{{s}}}",
  },
  {
    c: "Online Services",
    d: "www.google.com",
    r: 150000,
    s: "Google Maps",
    sc: "Maps",
    t: "gm",
    u: "https://www.google.com/maps/search/{{{s}}}",
  },
  {
    c: "Online Services",
    d: "www.deepl.com",
    r: 30000,
    s: "DeepL",
    sc: "Translation",
    t: "deepl",
    u: "https://www.deepl.com/translator#auto/en/{{{s}}}",
  },
];
